### ISSUE TITLE
Flags don't take precedence over values in config files

### ISSUE THREAD

**Issue by bartoszmajsak** [aslakknutsen/istio-workspace#26]
With config file

```yaml
develop:
  deployment: test
  run: "python3 server.py"
  port: 5555
```
and CLI call:

```shell
$ ike develop -r './test.sh'`
```

Telepresence should be called with `--run  './test.sh'`, but is with `--run 'python3 server.py'`.
